## Environment Setup & Dependencies

In [7]:
import os
import cv2
import librosa
import numpy as np
import pandas as pd

from itertools import combinations

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Input,
    Dense,
    Dropout
)

## 1D Signal Processing & Feature Extraction
Define a robust extraction function to compute summary statistics (mean and standard deviation) for five core audio attributes:
* **MFCCs**: 16 bands resulting in 32 dimensions.
* **Spectral Centroid**: Brightness of the sound.
* **RMS**: Signal energy.
* **ZCR**: Zero-crossing rate.
* **Pitch (F0)**: Fundamental frequency extracted via the YIN algorithm (50Hz - 1000Hz).

In [8]:
def extract_features(y, sr):

    # MFCC
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=16)
    mfcc_mean = np.mean(mfcc, axis=1)
    mfcc_std = np.std(mfcc, axis=1)

    mfcc_feature = np.concatenate([
        mfcc_mean,
        mfcc_std
    ])

    # shape = (32,)

    
    # SPECTRAL CENTROID
    centroid = librosa.feature.spectral_centroid(y=y, sr=sr)
    centroid_feature = np.array([
        np.mean(centroid),
        np.std(centroid)
    ])

    # shape = (2,)

    
    # RMS
    rms = librosa.feature.rms(y=y)
    rms_feature = np.array([
        np.mean(rms),
        np.std(rms)
    ])

    # shape = (2,)

    
    # ZCR
    zcr = librosa.feature.zero_crossing_rate(y)
    zcr_feature = np.array([
        np.mean(zcr),
        np.std(zcr)
    ])

    # shape = (2,)

    
    # PITCH
    f0 = librosa.yin(y, fmin=50, fmax=1000)
    f0 = f0[~np.isnan(f0)]

    if len(f0) > 0:
        pitch_feature = np.array([
            np.mean(f0),
            np.std(f0)
        ])

    else:
        pitch_feature = np.array([0, 0])

    # shape = (2,)

    return (
        mfcc_feature,
        centroid_feature,
        rms_feature,
        zcr_feature,
        pitch_feature
    )

## Data Ingestion & Preprocessing
Iterate through the directory structure to load raw audio files (`sr=16000`), extract the defined numerical features, and structure them into aligned lists mapping to their respective binary labels (Normal = 0, Sepsis = 1).

In [10]:
X_mfcc = []
X_centroid = []
X_rms = []
X_zcr = []
X_pitch = []

y_labels = []


def process_folder(folder_path, label):
    files = os.listdir(folder_path)
    for file in files:
        file_path = os.path.join(folder_path, file)

        try:
            # LOAD AUDIO
            y_audio, sr = librosa.load(
                file_path,
                sr=16000
            )

            # EXTRACT FEATURES
            (
                mfcc_feature,
                centroid_feature,
                rms_feature,
                zcr_feature,
                pitch_feature
            ) = extract_features(y_audio, sr)

            # SAVE FEATURES
            X_mfcc.append(mfcc_feature)
            X_centroid.append(centroid_feature)
            X_rms.append(rms_feature)
            X_zcr.append(zcr_feature)
            X_pitch.append(pitch_feature)
            y_labels.append(label)

        except Exception as e:
            print(f"Error processing {file_path}")
            print(e)


process_folder("dataset/normal", 0)
process_folder("dataset/sepsis", 1)

## Convert to NumPy Arrays

In [11]:
X_mfcc = np.array(X_mfcc)
X_centroid = np.array(X_centroid)
X_rms = np.array(X_rms)
X_zcr = np.array(X_zcr)
X_pitch = np.array(X_pitch)

y = np.array(y_labels)

print("MFCC Shape:", X_mfcc.shape)
print("Centroid Shape:", X_centroid.shape)
print("RMS Shape:", X_rms.shape)
print("ZCR Shape:", X_zcr.shape)
print("Pitch Shape:", X_pitch.shape)
print("Labels Shape:", y.shape)

MFCC Shape: (1817, 32)
Centroid Shape: (1817, 2)
RMS Shape: (1817, 2)
ZCR Shape: (1817, 2)
Pitch Shape: (1817, 2)
Labels Shape: (1817,)

## Combinatorial Feature Generation
Generate all $r$-length combinations of the extracted feature sets. This yields 31 unique configurations to comprehensively evaluate which combination of features holds the highest predictive power.

In [12]:
feature_dict = {
    "mfcc": X_mfcc,
    "centroid": X_centroid,
    "rms": X_rms,
    "zcr": X_zcr,
    "pitch": X_pitch
}

feature_names = list(feature_dict.keys())

all_combos = []

for r in range(1, len(feature_names) + 1):
    combos = combinations(feature_names, r)
    for combo in combos:
        all_combos.append(combo)

print("Total combinations:", len(all_combos))

print("\nAll combinations:\n")
for combo in all_combos:
    print(combo)

Total combinations: 31

All combinations:

('mfcc',)
('centroid',)
('rms',)
('zcr',)
('pitch',)
('mfcc', 'centroid')
('mfcc', 'rms')
('mfcc', 'zcr')
('mfcc', 'pitch')
('centroid', 'rms')
('centroid', 'zcr')
('centroid', 'pitch')
('rms', 'zcr')
('rms', 'pitch')
('zcr', 'pitch')
('mfcc', 'centroid', 'rms')
('mfcc', 'centroid', 'zcr')
('mfcc', 'centroid', 'pitch')
('mfcc', 'rms', 'zcr')
('mfcc', 'rms', 'pitch')
('mfcc', 'zcr', 'pitch')
('centroid', 'rms', 'zcr')
('centroid', 'rms', 'pitch')
('centroid', 'zcr', 'pitch')
('rms', 'zcr', 'pitch')
('mfcc', 'centroid', 'rms', 'zcr')
('mfcc', 'centroid', 'rms', 'pitch')
('mfcc', 'centroid', 'zcr', 'pitch')
('mfcc', 'rms', 'zcr', 'pitch')
('centroid', 'rms', 'zcr', 'pitch')
('mfcc', 'centroid', 'rms', 'zcr', 'pitch')

## MODEL FUNCTION

In [13]:
def build_numerical_model(input_dim):

    model = Sequential([

        Input(shape=(input_dim,)),

        Dense(128, activation='relu'),
        Dropout(0.3),

        Dense(64, activation='relu'),
        Dropout(0.2),

        Dense(32, activation='relu'),
        Dropout(0.1),

        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

## Ablation Experiment: Single-Seed Evaluation
Iterate through all 31 feature combinations to train and evaluate a Multilayer Perceptron (MLP). The dataset is standardized and split (80/20) using a single random seed (42). Predictions are derived using a strict 0.4 probability threshold.

In [14]:
results = []

for combo in all_combos:

    print("\n========================================")
    print("Training on:", combo)

    # CONCAT FEATURES
    X = np.concatenate(
        [feature_dict[f] for f in combo],
        axis=1
    )

    print("Combined Shape:", X.shape)

    # TRAIN TEST SPLIT
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    # STANDARDIZATION
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # BUILD MODEL
    model = build_numerical_model(
        input_dim=X_train.shape[1]
    )

    # TRAIN MODEL
    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_test, y_test),
        epochs=10,
        batch_size=32,
        verbose=0
    )

    # PREDICTIONS
    threshold = 0.4
    y_prob = model.predict(X_test, verbose=0)
    y_pred = (y_prob > threshold).astype(int).reshape(-1)

    # METRICS
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob.ravel())

    # SAVE RESULTS
    results.append({
        "Features": " + ".join(combo),
        "Accuracy": acc,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "ROC_AUC": auc
    })

    # PRINT RESULTS
    print("Accuracy :", round(acc, 4))
    print("Precision:", round(precision, 4))
    print("Recall   :", round(recall, 4))
    print("F1 Score :", round(f1, 4))
    print("ROC AUC  :", round(auc, 4))

========================================
Training on: ('mfcc',)
Combined Shape: (1817, 32)
WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Accuracy : 0.978
Precision: 0.9822
Recall   : 0.9708
F1 Score : 0.9765
ROC AUC  : 0.9986

========================================
Training on: ('centroid',)
Combined Shape: (1817, 2)
Accuracy : 0.6978
Precision: 0.6473
Recall   : 0.7836
F1 Score : 0.709
ROC AUC  : 0.7495

========================================
Training on: ('rms',)
Combined Shape: (1817, 2)
Accuracy : 0.7473
Precision: 0.6946
Recall   : 0.8246
F1 Score : 0.754
ROC AUC  : 0.8236

========================================
Training on: ('zcr',)
Combined Shape: (1817, 2)
Accuracy : 0.5412
Precision: 0.5076
Recall   : 0.7836
F1 Score : 0.6161
ROC AUC  : 0.6241

========================================
Training on: ('pitch',)
Combined Shape: (1817, 2)
Accuracy : 0.7198
Precision: 0.6683
Recall   : 0.8012
F1 Score : 0.7287
ROC AUC  : 0.7714

========================================
Training on: ('mfcc', 'centroid')
Combined Shape: (1817, 34)
Accuracy : 0.9835
Precision: 0.9882
Recall   : 0.9766
F1 Score : 0.9824
ROC AUC  : 0.9993

========================================
Training on: ('mfcc', 'rms')
Combined Shape: (1817, 34)
Accuracy : 0.9945
Precision: 0.9884
Recall   : 1.0
F1 Score : 0.9942
ROC AUC  : 0.9998

========================================
Training on: ('mfcc', 'zcr')
Combined Shape: (1817, 34)
Accuracy : 0.9808
Precision: 0.9824
Recall   : 0.9766
F1 Score : 0.9795
ROC AUC  : 0.9992

========================================
Training on: ('mfcc', 'pitch')
Combined Shape: (1817, 34)
Accuracy : 0.9808
Precision: 0.9767
Recall   : 0.9825
F1 Score : 0.9796
ROC AUC  : 0.9992

========================================
Training on: ('centroid', 'rms')
Combined Shape: (1817, 4)
Accuracy : 0.8297
Precision: 0.7978
Recall   : 0.8538
F1 Score : 0.8249
ROC AUC  : 0.9113

========================================
Training on: ('centroid', 'zcr')
Combined Shape: (1817, 4)
Accuracy : 0.8599
Precision: 0.9
Recall   : 0.7895
F1 Score : 0.8411
ROC AUC  : 0.9262

========================================
Training on: ('centroid', 'pitch')
Combined Shape: (1817, 4)
Accuracy : 0.783
Precision: 0.7527
Recall   : 0.8012
F1 Score : 0.7762
ROC AUC  : 0.855

========================================
Training on: ('rms', 'zcr')
Combined Shape: (1817, 4)
Accuracy : 0.7335
Precision: 0.6609
Recall   : 0.8889
F1 Score : 0.7581
ROC AUC  : 0.8341

========================================
Training on: ('rms', 'pitch')
Combined Shape: (1817, 4)
Accuracy : 0.8434
Precision: 0.7969
Recall   : 0.8947
F1 Score : 0.843
ROC AUC  : 0.904

========================================
Training on: ('zcr', 'pitch')
Combined Shape: (1817, 4)
Accuracy : 0.7857
Precision: 0.7268
Recall   : 0.8713
F1 Score : 0.7926
ROC AUC  : 0.8497

========================================
Training on: ('mfcc', 'centroid', 'rms')
Combined Shape: (1817, 36)
Accuracy : 0.9835
Precision: 0.9825
Recall   : 0.9825
F1 Score : 0.9825
ROC AUC  : 0.9992

========================================
Training on: ('mfcc', 'centroid', 'zcr')
Combined Shape: (1817, 36)
Accuracy : 0.9725
Precision: 0.982
Recall   : 0.9591
F1 Score : 0.9704
ROC AUC  : 0.9985

========================================
Training on: ('mfcc', 'centroid', 'pitch')
Combined Shape: (1817, 36)
Accuracy : 0.9835
Precision: 0.9769
Recall   : 0.9883
F1 Score : 0.9826
ROC AUC  : 0.9992

========================================
Training on: ('mfcc', 'rms', 'zcr')
Combined Shape: (1817, 36)
Accuracy : 0.9863
Precision: 0.9882
Recall   : 0.9825
F1 Score : 0.9853
ROC AUC  : 0.9988

========================================
Training on: ('mfcc', 'rms', 'pitch')
Combined Shape: (1817, 36)
Accuracy : 0.9808
Precision: 0.9824
Recall   : 0.9766
F1 Score : 0.9795
ROC AUC  : 0.9972

========================================
Training on: ('mfcc', 'zcr', 'pitch')
Combined Shape: (1817, 36)
Accuracy : 0.978
Precision: 0.9766
Recall   : 0.9766
F1 Score : 0.9766
ROC AUC  : 0.9988

========================================
Training on: ('centroid', 'rms', 'zcr')
Combined Shape: (1817, 6)
Accuracy : 0.9258
Precision: 0.9186
Recall   : 0.924
F1 Score : 0.9213
ROC AUC  : 0.9744

========================================
Training on: ('centroid', 'rms', 'pitch')
Combined Shape: (1817, 6)
Accuracy : 0.8736
Precision: 0.8492
Recall   : 0.8889
F1 Score : 0.8686
ROC AUC  : 0.9351

========================================
Training on: ('centroid', 'zcr', 'pitch')
Combined Shape: (1817, 6)
Accuracy : 0.8819
Precision: 0.8951
Recall   : 0.848
F1 Score : 0.8709
ROC AUC  : 0.9439

========================================
Training on: ('rms', 'zcr', 'pitch')
Combined Shape: (1817, 6)
Accuracy : 0.8544
Precision: 0.8207
Recall   : 0.883
F1 Score : 0.8507
ROC AUC  : 0.9039

========================================
Training on: ('mfcc', 'centroid', 'rms', 'zcr')
Combined Shape: (1817, 38)
Accuracy : 0.989
Precision: 0.9941
Recall   : 0.9825
F1 Score : 0.9882
ROC AUC  : 0.999

========================================
Training on: ('mfcc', 'centroid', 'rms', 'pitch')
Combined Shape: (1817, 38)
Accuracy : 0.9753
Precision: 0.9765
Recall   : 0.9708
F1 Score : 0.9736
ROC AUC  : 0.9993

========================================
Training on: ('mfcc', 'centroid', 'zcr', 'pitch')
Combined Shape: (1817, 38)
Accuracy : 0.9918
Precision: 0.9884
Recall   : 0.9942
F1 Score : 0.9913
ROC AUC  : 0.9993

========================================
Training on: ('mfcc', 'rms', 'zcr', 'pitch')
Combined Shape: (1817, 38)
Accuracy : 0.9725
Precision: 0.9708
Recall   : 0.9708
F1 Score : 0.9708
ROC AUC  : 0.9982

========================================
Training on: ('centroid', 'rms', 'zcr', 'pitch')
Combined Shape: (1817, 8)
Accuracy : 0.9258
Precision: 0.9091
Recall   : 0.9357
F1 Score : 0.9222
ROC AUC  : 0.9728

========================================
Training on: ('mfcc', 'centroid', 'rms', 'zcr', 'pitch')
Combined Shape: (1817, 40)
Accuracy : 0.978
Precision: 0.9766
Recall   : 0.9766
F1 Score : 0.9766
ROC AUC  : 0.9988

## CREATE RESULTS DATAFRAME

In [32]:
df = pd.DataFrame(results)
df = df.sort_values(
    by="Recall",
    ascending=False
)

# SHOW TOP RESULTS
print("\n========================================")
print("TOP 10 RESULTS")
print("========================================\n")

df.head(10)

========================================
TOP 10 RESULTS
========================================

,Features,Accuracy,Precision,Recall,F1,ROC_AUC
6,mfcc + rms,0.994505,0.988439,1.000000,0.994186,0.999818
27,mfcc + centroid + zcr + pitch,0.991758,0.988372,0.994152,0.991254,0.999303
17,mfcc + centroid + pitch,0.983516,0.976879,0.988304,0.982558,0.999242
15,mfcc + centroid + rms,0.983516,0.982456,0.982456,0.982456,0.999152
18,mfcc + rms + zcr,0.986264,0.988235,0.982456,0.985337,0.998788
8,mfcc + pitch,0.980769,0.976744,0.982456,0.979592,0.999212
25,mfcc + centroid + rms + zcr,0.989011,0.994083,0.982456,0.988235,0.999000
19,mfcc + rms + pitch,0.980769,0.982353,0.976608,0.979472,0.997182
20,mfcc + zcr + pitch,0.978022,0.976608,0.976608,0.976608,0.998818
30,mfcc + centroid + rms + zcr + pitch,0.978022,0.976608,0.976608,0.976608,0.998788

# SAVE RESULTS CSV

In [ ]:
df.to_csv(
    "numerical_feature_ablation_results.csv",
    index=False
)

print("\nResults saved successfully!")

## Robustness Testing: Multi-Seed Cross Validation
To ensure the feature combinations are stable and not overfitting to a specific train-test split, re-evaluate all 31 combinations across three distinct random states (42, 357, 999). Metrics are aggregated to report the mean performance.

In [47]:
random_states = [42, 357, 999]
results = []

for combo in all_combos:

    print("\n========================================")
    print("Training on:", combo)

    # CONCAT FEATURES
    X = np.concatenate(
        [feature_dict[f] for f in combo],
        axis=1
    )

    print("Combined Shape:", X.shape)

    # STORE METRICS OF 3 SPLITS
    acc_list = []
    precision_list = []
    recall_list = []
    f1_list = []
    auc_list = []

    
    # 3 DIFFERENT TRAIN-TEST SPLITS
    for rs in random_states:
        print(f"\n--- Random State: {rs} ---")

        # TRAIN TEST SPLIT
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.2,
            random_state=rs,
            stratify=y
        )

        # STANDARDIZATION
        scaler = StandardScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)

        # BUILD MODEL
        model = build_numerical_model(
            input_dim=X_train.shape[1]
        )

        # TRAIN MODEL
        model.fit(
            X_train,
            y_train,
            validation_data=(X_test, y_test),
            epochs=10,
            batch_size=32,
            verbose=0
        )

        # PREDICTIONS
        threshold = 0.4
        y_prob = model.predict(X_test, verbose=0)
        y_pred = (y_prob > threshold).astype(int).reshape(-1)

        # METRICS
        acc = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        auc = roc_auc_score(y_test, y_prob.ravel())

        # SAVE CURRENT SPLIT METRICS
        acc_list.append(acc)
        precision_list.append(precision)
        recall_list.append(recall)
        f1_list.append(f1)
        auc_list.append(auc)

        # PRINT CURRENT SPLIT RESULTS
        print("Accuracy :", round(acc, 4))
        print("Precision:", round(precision, 4))
        print("Recall   :", round(recall, 4))
        print("F1 Score :", round(f1, 4))
        print("ROC AUC  :", round(auc, 4))

    
    # AVERAGE RESULTS OF 3 SPLITS
    avg_acc = np.mean(acc_list)
    avg_precision = np.mean(precision_list)
    avg_recall = np.mean(recall_list)
    avg_f1 = np.mean(f1_list)
    avg_auc = np.mean(auc_list)

    std_acc = np.std(acc_list)
    std_precision = np.std(precision_list)
    std_recall = np.std(recall_list)
    std_f1 = np.std(f1_list)
    std_auc = np.std(auc_list)

    # SAVE FINAL AVERAGE RESULT
    results.append({
        "Features": " + ".join(combo),
        "Accuracy": avg_acc,
        "Precision": avg_precision,
        "Recall": avg_recall,
        "F1": avg_f1,
        "ROC_AUC": avg_auc,
    })

    # PRINT FINAL AVG RESULTS
    print("\n===== AVERAGE RESULTS =====")

    print("Avg Accuracy :", round(avg_acc, 4))
    print("Avg Precision:", round(avg_precision, 4))
    print("Avg Recall   :", round(avg_recall, 4))
    print("Avg F1 Score :", round(avg_f1, 4))
    print("Avg ROC AUC  :", round(avg_auc, 4))

========================================
Training on: ('mfcc',)
Combined Shape: (1817, 32)

--- Random State: 42 ---
Accuracy : 0.978
Precision: 0.9822
Recall   : 0.9708
F1 Score : 0.9765
ROC AUC  : 0.9983

--- Random State: 357 ---
Accuracy : 0.9808
Precision: 0.9713
Recall   : 0.9883
F1 Score : 0.9797
ROC AUC  : 0.9981

--- Random State: 999 ---
Accuracy : 0.9643
Precision: 0.954
Recall   : 0.9708
F1 Score : 0.9623
ROC AUC  : 0.9917

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9744
Avg Precision: 0.9692
Avg Recall   : 0.9766
Avg F1 Score : 0.9728
Avg ROC AUC  : 0.996

========================================
Training on: ('centroid',)
Combined Shape: (1817, 2)

--- Random State: 42 ---
Accuracy : 0.6951
Precision: 0.6456
Recall   : 0.7778
F1 Score : 0.7056
ROC AUC  : 0.7536

--- Random State: 357 ---
Accuracy : 0.7143
Precision: 0.6736
Recall   : 0.7602
F1 Score : 0.7143
ROC AUC  : 0.7364

--- Random State: 999 ---
Accuracy : 0.6429
Precision: 0.599
Recall   : 0.7251
F1 Score : 0.6561
ROC AUC  : 0.6779

===== AVERAGE RESULTS =====
Avg Accuracy : 0.6841
Avg Precision: 0.6394
Avg Recall   : 0.7544
Avg F1 Score : 0.692
Avg ROC AUC  : 0.7226

========================================
Training on: ('rms',)
Combined Shape: (1817, 2)

--- Random State: 42 ---
Accuracy : 0.7198
Precision: 0.6533
Recall   : 0.8596
F1 Score : 0.7424
ROC AUC  : 0.8254

--- Random State: 357 ---
Accuracy : 0.7143
Precision: 0.6634
Recall   : 0.7953
F1 Score : 0.7234
ROC AUC  : 0.8023

--- Random State: 999 ---
Accuracy : 0.739
Precision: 0.681
Recall   : 0.8363
F1 Score : 0.7507
ROC AUC  : 0.8221

===== AVERAGE RESULTS =====
Avg Accuracy : 0.7244
Avg Precision: 0.6659
Avg Recall   : 0.8304
Avg F1 Score : 0.7388
Avg ROC AUC  : 0.8166

========================================
Training on: ('zcr',)
Combined Shape: (1817, 2)

--- Random State: 42 ---
Accuracy : 0.5495
Precision: 0.5129
Recall   : 0.8129
F1 Score : 0.629
ROC AUC  : 0.6214

--- Random State: 357 ---
Accuracy : 0.5165
Precision: 0.4915
Recall   : 0.848
F1 Score : 0.6223
ROC AUC  : 0.6165

--- Random State: 999 ---
Accuracy : 0.5385
Precision: 0.5051
Recall   : 0.8713
F1 Score : 0.6395
ROC AUC  : 0.614

===== AVERAGE RESULTS =====
Avg Accuracy : 0.5348
Avg Precision: 0.5032
Avg Recall   : 0.8441
Avg F1 Score : 0.6303
Avg ROC AUC  : 0.6173

========================================
Training on: ('pitch',)
Combined Shape: (1817, 2)

--- Random State: 42 ---
Accuracy : 0.7088
Precision: 0.6617
Recall   : 0.7778
F1 Score : 0.7151
ROC AUC  : 0.7715

--- Random State: 357 ---
Accuracy : 0.7143
Precision: 0.6618
Recall   : 0.8012
F1 Score : 0.7249
ROC AUC  : 0.7857

--- Random State: 999 ---
Accuracy : 0.717
Precision: 0.6635
Recall   : 0.807
F1 Score : 0.7282
ROC AUC  : 0.798

===== AVERAGE RESULTS =====
Avg Accuracy : 0.7134
Avg Precision: 0.6623
Avg Recall   : 0.7953
Avg F1 Score : 0.7227
Avg ROC AUC  : 0.785

========================================
Training on: ('mfcc', 'centroid')
Combined Shape: (1817, 34)

--- Random State: 42 ---
Accuracy : 0.967
Precision: 0.976
Recall   : 0.9532
F1 Score : 0.9645
ROC AUC  : 0.9974

--- Random State: 357 ---
Accuracy : 0.978
Precision: 0.9605
Recall   : 0.9942
F1 Score : 0.977
ROC AUC  : 0.9988

--- Random State: 999 ---
Accuracy : 0.9725
Precision: 0.9708
Recall   : 0.9708
F1 Score : 0.9708
ROC AUC  : 0.9911

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9725
Avg Precision: 0.9691
Avg Recall   : 0.9727
Avg F1 Score : 0.9708
Avg ROC AUC  : 0.9958

========================================
Training on: ('mfcc', 'rms')
Combined Shape: (1817, 34)

--- Random State: 42 ---
Accuracy : 0.9835
Precision: 0.994
Recall   : 0.9708
F1 Score : 0.9822
ROC AUC  : 0.9989

--- Random State: 357 ---
Accuracy : 0.9808
Precision: 0.9713
Recall   : 0.9883
F1 Score : 0.9797
ROC AUC  : 0.9988

--- Random State: 999 ---
Accuracy : 0.956
Precision: 0.9532
Recall   : 0.9532
F1 Score : 0.9532
ROC AUC  : 0.9888

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9734
Avg Precision: 0.9728
Avg Recall   : 0.9708
Avg F1 Score : 0.9717
Avg ROC AUC  : 0.9955

========================================
Training on: ('mfcc', 'zcr')
Combined Shape: (1817, 34)

--- Random State: 42 ---
Accuracy : 0.978
Precision: 0.9766
Recall   : 0.9766
F1 Score : 0.9766
ROC AUC  : 0.9985

--- Random State: 357 ---
Accuracy : 0.978
Precision: 0.9711
Recall   : 0.9825
F1 Score : 0.9767
ROC AUC  : 0.9975

--- Random State: 999 ---
Accuracy : 0.9643
Precision: 0.9593
Recall   : 0.9649
F1 Score : 0.9621
ROC AUC  : 0.9933

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9734
Avg Precision: 0.969
Avg Recall   : 0.9747
Avg F1 Score : 0.9718
Avg ROC AUC  : 0.9964

========================================
Training on: ('mfcc', 'pitch')
Combined Shape: (1817, 34)

--- Random State: 42 ---
Accuracy : 0.989
Precision: 0.9883
Recall   : 0.9883
F1 Score : 0.9883
ROC AUC  : 0.9988

--- Random State: 357 ---
Accuracy : 0.9753
Precision: 0.9602
Recall   : 0.9883
F1 Score : 0.9741
ROC AUC  : 0.996

--- Random State: 999 ---
Accuracy : 0.9643
Precision: 0.9647
Recall   : 0.9591
F1 Score : 0.9619
ROC AUC  : 0.9914

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9762
Avg Precision: 0.9711
Avg Recall   : 0.9786
Avg F1 Score : 0.9747
Avg ROC AUC  : 0.9954

========================================
Training on: ('centroid', 'rms')
Combined Shape: (1817, 4)

--- Random State: 42 ---
Accuracy : 0.8352
Precision: 0.7968
Recall   : 0.8713
F1 Score : 0.8324
ROC AUC  : 0.9133

--- Random State: 357 ---
Accuracy : 0.7995
Precision: 0.7722
Recall   : 0.8129
F1 Score : 0.792
ROC AUC  : 0.8874

--- Random State: 999 ---
Accuracy : 0.8132
Precision: 0.7725
Recall   : 0.8538
F1 Score : 0.8111
ROC AUC  : 0.8883

===== AVERAGE RESULTS =====
Avg Accuracy : 0.8159
Avg Precision: 0.7805
Avg Recall   : 0.846
Avg F1 Score : 0.8118
Avg ROC AUC  : 0.8963

========================================
Training on: ('centroid', 'zcr')
Combined Shape: (1817, 4)

--- Random State: 42 ---
Accuracy : 0.8516
Precision: 0.8926
Recall   : 0.7778
F1 Score : 0.8313
ROC AUC  : 0.9222

--- Random State: 357 ---
Accuracy : 0.8187
Precision: 0.8107
Recall   : 0.8012
F1 Score : 0.8059
ROC AUC  : 0.9073

--- Random State: 999 ---
Accuracy : 0.794
Precision: 0.7857
Recall   : 0.7719
F1 Score : 0.7788
ROC AUC  : 0.8936

===== AVERAGE RESULTS =====
Avg Accuracy : 0.8214
Avg Precision: 0.8297
Avg Recall   : 0.7836
Avg F1 Score : 0.8053
Avg ROC AUC  : 0.9077

========================================
Training on: ('centroid', 'pitch')
Combined Shape: (1817, 4)

--- Random State: 42 ---
Accuracy : 0.7775
Precision: 0.7557
Recall   : 0.7778
F1 Score : 0.7666
ROC AUC  : 0.8568

--- Random State: 357 ---
Accuracy : 0.8214
Precision: 0.8313
Recall   : 0.7778
F1 Score : 0.8036
ROC AUC  : 0.8631

--- Random State: 999 ---
Accuracy : 0.7555
Precision: 0.7562
Recall   : 0.7076
F1 Score : 0.7311
ROC AUC  : 0.8222

===== AVERAGE RESULTS =====
Avg Accuracy : 0.7848
Avg Precision: 0.7811
Avg Recall   : 0.7544
Avg F1 Score : 0.7671
Avg ROC AUC  : 0.8474

========================================
Training on: ('rms', 'zcr')
Combined Shape: (1817, 4)

--- Random State: 42 ---
Accuracy : 0.7363
Precision: 0.6682
Recall   : 0.8713
F1 Score : 0.7563
ROC AUC  : 0.8355

--- Random State: 357 ---
Accuracy : 0.7473
Precision: 0.7112
Recall   : 0.7778
F1 Score : 0.743
ROC AUC  : 0.8179

--- Random State: 999 ---
Accuracy : 0.7747
Precision: 0.7129
Recall   : 0.8713
F1 Score : 0.7842
ROC AUC  : 0.8375

===== AVERAGE RESULTS =====
Avg Accuracy : 0.7527
Avg Precision: 0.6974
Avg Recall   : 0.8402
Avg F1 Score : 0.7612
Avg ROC AUC  : 0.8303

========================================
Training on: ('rms', 'pitch')
Combined Shape: (1817, 4)

--- Random State: 42 ---
Accuracy : 0.8379
Precision: 0.7887
Recall   : 0.8947
F1 Score : 0.8384
ROC AUC  : 0.9009

--- Random State: 357 ---
Accuracy : 0.7995
Precision: 0.7692
Recall   : 0.8187
F1 Score : 0.7932
ROC AUC  : 0.8899

--- Random State: 999 ---
Accuracy : 0.8489
Precision: 0.8222
Recall   : 0.8655
F1 Score : 0.8433
ROC AUC  : 0.9048

===== AVERAGE RESULTS =====
Avg Accuracy : 0.8288
Avg Precision: 0.7934
Avg Recall   : 0.8596
Avg F1 Score : 0.825
Avg ROC AUC  : 0.8985

========================================
Training on: ('zcr', 'pitch')
Combined Shape: (1817, 4)

--- Random State: 42 ---
Accuracy : 0.783
Precision: 0.7255
Recall   : 0.8655
F1 Score : 0.7893
ROC AUC  : 0.8476

--- Random State: 357 ---
Accuracy : 0.7418
Precision: 0.6791
Recall   : 0.8538
F1 Score : 0.7565
ROC AUC  : 0.8336

--- Random State: 999 ---
Accuracy : 0.761
Precision: 0.7143
Recall   : 0.8187
F1 Score : 0.7629
ROC AUC  : 0.8285

===== AVERAGE RESULTS =====
Avg Accuracy : 0.7619
Avg Precision: 0.7063
Avg Recall   : 0.846
Avg F1 Score : 0.7696
Avg ROC AUC  : 0.8366

========================================
Training on: ('mfcc', 'centroid', 'rms')
Combined Shape: (1817, 36)

--- Random State: 42 ---
Accuracy : 0.9808
Precision: 0.9824
Recall   : 0.9766
F1 Score : 0.9795
ROC AUC  : 0.998

--- Random State: 357 ---
Accuracy : 0.978
Precision: 0.9657
Recall   : 0.9883
F1 Score : 0.9769
ROC AUC  : 0.9981

--- Random State: 999 ---
Accuracy : 0.9588
Precision: 0.9588
Recall   : 0.9532
F1 Score : 0.956
ROC AUC  : 0.9915

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9725
Avg Precision: 0.969
Avg Recall   : 0.9727
Avg F1 Score : 0.9708
Avg ROC AUC  : 0.9959

========================================
Training on: ('mfcc', 'centroid', 'zcr')
Combined Shape: (1817, 36)

--- Random State: 42 ---
Accuracy : 0.9808
Precision: 0.9824
Recall   : 0.9766
F1 Score : 0.9795
ROC AUC  : 0.9981

--- Random State: 357 ---
Accuracy : 0.978
Precision: 0.9605
Recall   : 0.9942
F1 Score : 0.977
ROC AUC  : 0.999

--- Random State: 999 ---
Accuracy : 0.9533
Precision: 0.9583
Recall   : 0.9415
F1 Score : 0.9499
ROC AUC  : 0.9924

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9707
Avg Precision: 0.967
Avg Recall   : 0.9708
Avg F1 Score : 0.9688
Avg ROC AUC  : 0.9965

========================================
Training on: ('mfcc', 'centroid', 'pitch')
Combined Shape: (1817, 36)

--- Random State: 42 ---
Accuracy : 0.9808
Precision: 0.9881
Recall   : 0.9708
F1 Score : 0.9794
ROC AUC  : 0.9988

--- Random State: 357 ---
Accuracy : 0.9808
Precision: 0.9713
Recall   : 0.9883
F1 Score : 0.9797
ROC AUC  : 0.9967

--- Random State: 999 ---
Accuracy : 0.967
Precision: 0.9595
Recall   : 0.9708
F1 Score : 0.9651
ROC AUC  : 0.9919

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9762
Avg Precision: 0.973
Avg Recall   : 0.9766
Avg F1 Score : 0.9747
Avg ROC AUC  : 0.9958

========================================
Training on: ('mfcc', 'rms', 'zcr')
Combined Shape: (1817, 36)

--- Random State: 42 ---
Accuracy : 0.9863
Precision: 0.9826
Recall   : 0.9883
F1 Score : 0.9854
ROC AUC  : 0.9993

--- Random State: 357 ---
Accuracy : 0.978
Precision: 0.9657
Recall   : 0.9883
F1 Score : 0.9769
ROC AUC  : 0.9988

--- Random State: 999 ---
Accuracy : 0.9588
Precision: 0.9483
Recall   : 0.9649
F1 Score : 0.9565
ROC AUC  : 0.993

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9744
Avg Precision: 0.9655
Avg Recall   : 0.9805
Avg F1 Score : 0.9729
Avg ROC AUC  : 0.9971

========================================
Training on: ('mfcc', 'rms', 'pitch')
Combined Shape: (1817, 36)

--- Random State: 42 ---
Accuracy : 0.9808
Precision: 0.9767
Recall   : 0.9825
F1 Score : 0.9796
ROC AUC  : 0.9988

--- Random State: 357 ---
Accuracy : 0.978
Precision: 0.9711
Recall   : 0.9825
F1 Score : 0.9767
ROC AUC  : 0.9987

--- Random State: 999 ---
Accuracy : 0.9698
Precision: 0.9651
Recall   : 0.9708
F1 Score : 0.9679
ROC AUC  : 0.9936

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9762
Avg Precision: 0.971
Avg Recall   : 0.9786
Avg F1 Score : 0.9748
Avg ROC AUC  : 0.997

========================================
Training on: ('mfcc', 'zcr', 'pitch')
Combined Shape: (1817, 36)

--- Random State: 42 ---
Accuracy : 0.978
Precision: 0.9822
Recall   : 0.9708
F1 Score : 0.9765
ROC AUC  : 0.9991

--- Random State: 357 ---
Accuracy : 0.9835
Precision: 0.9769
Recall   : 0.9883
F1 Score : 0.9826
ROC AUC  : 0.9979

--- Random State: 999 ---
Accuracy : 0.9588
Precision: 0.9643
Recall   : 0.9474
F1 Score : 0.9558
ROC AUC  : 0.994

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9734
Avg Precision: 0.9745
Avg Recall   : 0.9688
Avg F1 Score : 0.9716
Avg ROC AUC  : 0.997

========================================
Training on: ('centroid', 'rms', 'zcr')
Combined Shape: (1817, 6)

--- Random State: 42 ---
Accuracy : 0.9148
Precision: 0.907
Recall   : 0.9123
F1 Score : 0.9096
ROC AUC  : 0.9714

--- Random State: 357 ---
Accuracy : 0.8984
Precision: 0.8851
Recall   : 0.9006
F1 Score : 0.8928
ROC AUC  : 0.9523

--- Random State: 999 ---
Accuracy : 0.8764
Precision: 0.85
Recall   : 0.8947
F1 Score : 0.8718
ROC AUC  : 0.9545

===== AVERAGE RESULTS =====
Avg Accuracy : 0.8965
Avg Precision: 0.8807
Avg Recall   : 0.9025
Avg F1 Score : 0.8914
Avg ROC AUC  : 0.9594

========================================
Training on: ('centroid', 'rms', 'pitch')
Combined Shape: (1817, 6)

--- Random State: 42 ---
Accuracy : 0.8654
Precision: 0.8427
Recall   : 0.8772
F1 Score : 0.8596
ROC AUC  : 0.9368

--- Random State: 357 ---
Accuracy : 0.8516
Precision: 0.8421
Recall   : 0.8421
F1 Score : 0.8421
ROC AUC  : 0.9235

--- Random State: 999 ---
Accuracy : 0.8626
Precision: 0.858
Recall   : 0.848
F1 Score : 0.8529
ROC AUC  : 0.9231

===== AVERAGE RESULTS =====
Avg Accuracy : 0.8599
Avg Precision: 0.8476
Avg Recall   : 0.8558
Avg F1 Score : 0.8515
Avg ROC AUC  : 0.9278

========================================
Training on: ('centroid', 'zcr', 'pitch')
Combined Shape: (1817, 6)

--- Random State: 42 ---
Accuracy : 0.8956
Precision: 0.913
Recall   : 0.8596
F1 Score : 0.8855
ROC AUC  : 0.9449

--- Random State: 357 ---
Accuracy : 0.8544
Precision: 0.8278
Recall   : 0.8713
F1 Score : 0.849
ROC AUC  : 0.9313

--- Random State: 999 ---
Accuracy : 0.8352
Precision: 0.8535
Recall   : 0.7836
F1 Score : 0.8171
ROC AUC  : 0.9156

===== AVERAGE RESULTS =====
Avg Accuracy : 0.8617
Avg Precision: 0.8648
Avg Recall   : 0.8382
Avg F1 Score : 0.8505
Avg ROC AUC  : 0.9306

========================================
Training on: ('rms', 'zcr', 'pitch')
Combined Shape: (1817, 6)

--- Random State: 42 ---
Accuracy : 0.8434
Precision: 0.7879
Recall   : 0.9123
F1 Score : 0.8455
ROC AUC  : 0.9061

--- Random State: 357 ---
Accuracy : 0.8214
Precision: 0.8118
Recall   : 0.807
F1 Score : 0.8094
ROC AUC  : 0.9001

--- Random State: 999 ---
Accuracy : 0.8352
Precision: 0.7876
Recall   : 0.8889
F1 Score : 0.8352
ROC AUC  : 0.9054

===== AVERAGE RESULTS =====
Avg Accuracy : 0.8333
Avg Precision: 0.7957
Avg Recall   : 0.8694
Avg F1 Score : 0.83
Avg ROC AUC  : 0.9039

========================================
Training on: ('mfcc', 'centroid', 'rms', 'zcr')
Combined Shape: (1817, 38)

--- Random State: 42 ---
Accuracy : 0.9863
Precision: 0.9882
Recall   : 0.9825
F1 Score : 0.9853
ROC AUC  : 0.9992

--- Random State: 357 ---
Accuracy : 0.9835
Precision: 0.9714
Recall   : 0.9942
F1 Score : 0.9827
ROC AUC  : 0.9984

--- Random State: 999 ---
Accuracy : 0.9533
Precision: 0.9425
Recall   : 0.9591
F1 Score : 0.9507
ROC AUC  : 0.9935

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9744
Avg Precision: 0.9674
Avg Recall   : 0.9786
Avg F1 Score : 0.9729
Avg ROC AUC  : 0.997

========================================
Training on: ('mfcc', 'centroid', 'rms', 'pitch')
Combined Shape: (1817, 38)

--- Random State: 42 ---
Accuracy : 0.9808
Precision: 0.9767
Recall   : 0.9825
F1 Score : 0.9796
ROC AUC  : 0.9987

--- Random State: 357 ---
Accuracy : 0.9753
Precision: 0.9709
Recall   : 0.9766
F1 Score : 0.9738
ROC AUC  : 0.9985

--- Random State: 999 ---
Accuracy : 0.967
Precision: 0.9649
Recall   : 0.9649
F1 Score : 0.9649
ROC AUC  : 0.9923

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9744
Avg Precision: 0.9709
Avg Recall   : 0.9747
Avg F1 Score : 0.9728
Avg ROC AUC  : 0.9965

========================================
Training on: ('mfcc', 'centroid', 'zcr', 'pitch')
Combined Shape: (1817, 38)

--- Random State: 42 ---
Accuracy : 0.989
Precision: 0.9941
Recall   : 0.9825
F1 Score : 0.9882
ROC AUC  : 0.9997

--- Random State: 357 ---
Accuracy : 0.967
Precision: 0.9543
Recall   : 0.9766
F1 Score : 0.9653
ROC AUC  : 0.9966

--- Random State: 999 ---
Accuracy : 0.967
Precision: 0.9704
Recall   : 0.9591
F1 Score : 0.9647
ROC AUC  : 0.9948

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9744
Avg Precision: 0.9729
Avg Recall   : 0.9727
Avg F1 Score : 0.9728
Avg ROC AUC  : 0.997

========================================
Training on: ('mfcc', 'rms', 'zcr', 'pitch')
Combined Shape: (1817, 38)

--- Random State: 42 ---
Accuracy : 0.9863
Precision: 0.9826
Recall   : 0.9883
F1 Score : 0.9854
ROC AUC  : 0.9993

--- Random State: 357 ---
Accuracy : 0.9753
Precision: 0.9655
Recall   : 0.9825
F1 Score : 0.9739
ROC AUC  : 0.9985

--- Random State: 999 ---
Accuracy : 0.9505
Precision: 0.9422
Recall   : 0.9532
F1 Score : 0.9477
ROC AUC  : 0.9939

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9707
Avg Precision: 0.9634
Avg Recall   : 0.9747
Avg F1 Score : 0.969
Avg ROC AUC  : 0.9972

========================================
Training on: ('centroid', 'rms', 'zcr', 'pitch')
Combined Shape: (1817, 8)

--- Random State: 42 ---
Accuracy : 0.9203
Precision: 0.9176
Recall   : 0.9123
F1 Score : 0.915
ROC AUC  : 0.9689

--- Random State: 357 ---
Accuracy : 0.9148
Precision: 0.9217
Recall   : 0.8947
F1 Score : 0.908
ROC AUC  : 0.9565

--- Random State: 999 ---
Accuracy : 0.9038
Precision: 0.9
Recall   : 0.8947
F1 Score : 0.8974
ROC AUC  : 0.9577

===== AVERAGE RESULTS =====
Avg Accuracy : 0.913
Avg Precision: 0.9131
Avg Recall   : 0.9006
Avg F1 Score : 0.9068
Avg ROC AUC  : 0.961

========================================
Training on: ('mfcc', 'centroid', 'rms', 'zcr', 'pitch')
Combined Shape: (1817, 40)

--- Random State: 42 ---
Accuracy : 0.9835
Precision: 0.9714
Recall   : 0.9942
F1 Score : 0.9827
ROC AUC  : 0.9991

--- Random State: 357 ---
Accuracy : 0.9753
Precision: 0.9655
Recall   : 0.9825
F1 Score : 0.9739
ROC AUC  : 0.9976

--- Random State: 999 ---
Accuracy : 0.9533
Precision: 0.9639
Recall   : 0.9357
F1 Score : 0.9496
ROC AUC  : 0.9928

===== AVERAGE RESULTS =====
Avg Accuracy : 0.9707
Avg Precision: 0.9669
Avg Recall   : 0.9708
Avg F1 Score : 0.9687
Avg ROC AUC  : 0.9965

## CREATE RESULTS_2 DATAFRAME

In [50]:
df2 = pd.DataFrame(results)
df2 = df2.sort_values(
    by="Recall",
    ascending=False
)

# SHOW TOP RESULTS
print("\n========================================")
print("TOP 10 RESULTS")
print("========================================\n")

df2.head(10)

========================================
TOP 10 RESULTS
========================================

,Features,Accuracy,Precision,Recall,F1,ROC_AUC
18,mfcc + rms + zcr,0.974359,0.965516,0.980507,0.972941,0.997051
19,mfcc + rms + pitch,0.976190,0.970986,0.978558,0.974755,0.997031
8,mfcc + pitch,0.976190,0.971079,0.978558,0.974748,0.995394
25,mfcc + centroid + rms + zcr,0.974359,0.967398,0.978558,0.972907,0.997041
17,mfcc + centroid + pitch,0.976190,0.972966,0.976608,0.974726,0.995788
0,mfcc,0.974359,0.969179,0.976608,0.972833,0.996031
7,mfcc + zcr,0.973443,0.969003,0.974659,0.971817,0.996425
28,mfcc + rms + zcr + pitch,0.970696,0.963424,0.974659,0.969003,0.997233
26,mfcc + centroid + rms + pitch,0.974359,0.970862,0.974659,0.972755,0.996485
15,mfcc + centroid + rms,0.972527,0.968964,0.972710,0.970787,0.995859

# SAVE RESULTS CSV

In [51]:
df2.to_csv(
    "numerical_feature_ablation_3x_results.csv",
    index=False
)

print("\nResults saved successfully!")

Results saved successfully!